name: Publish Go Bindings

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Go Protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@1.5.4 
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@1.6.1

      - name: Generate Go Protobuf
        run: bash ./scripts/generate_go.sh
